package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"strings"
	model1 "system/internal/system/graph/model"
	"system/internal/system/model"
	"system/internal/system/repository"
	"time"
)

// Status is the resolver for the status field.
func (r *dashboardResolver) Status(ctx context.Context, obj *model.Dashboard) (model1.DashboardStatus, error) {
	switch obj.Status {
	case model.DashboardStatusDraft:
		return model1.DashboardStatusDraft, nil
	case model.DashboardStatusPublished:
		return model1.DashboardStatusPublished, nil
	case model.DashboardStatusChanged:
		return model1.DashboardStatusChanged, nil
	case model.DashboardStatusTrashed:
		return model1.DashboardStatusTrashed, nil
	default:
		return model1.DashboardStatusDraft, nil
	}
}

// DraftName is the resolver for the draftName field.
func (r *dashboardResolver) DraftName(ctx context.Context, obj *model.Dashboard) (*string, error) {
	if obj.DraftData != nil && obj.DraftData.Name != "" {
		return &obj.DraftData.Name, nil
	}
	return nil, nil
}

// DraftDescription is the resolver for the draftDescription field.
func (r *dashboardResolver) DraftDescription(ctx context.Context, obj *model.Dashboard) (*string, error) {
	if obj.DraftData != nil && obj.DraftData.Description != "" {
		return &obj.DraftData.Description, nil
	}
	return nil, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *dashboardResolver) CreatedAt(ctx context.Context, obj *model.Dashboard) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *dashboardResolver) UpdatedAt(ctx context.Context, obj *model.Dashboard) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// IsLocked is the resolver for the isLocked field.
func (r *dashboardResolver) IsLocked(ctx context.Context, obj *model.Dashboard) (bool, error) {
	lock, err := r.DashboardRepo.GetLock(ctx, obj.ID)
	if err != nil {
		return false, err
	}
	return lock != nil, nil
}

// LockedBy is the resolver for the lockedBy field.
func (r *dashboardResolver) LockedBy(ctx context.Context, obj *model.Dashboard) (*string, error) {
	lock, err := r.DashboardRepo.GetLock(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	if lock != nil {
		return &lock.LockedBy, nil
	}
	return nil, nil
}

// PublishedAt is the resolver for the publishedAt field.
func (r *dashboardHistoryResolver) PublishedAt(ctx context.Context, obj *model.DashboardHistory) (string, error) {
	return obj.PublishedAt.Format(time.RFC3339), nil
}

// LockedAt is the resolver for the lockedAt field.
func (r *dashboardLockResolver) LockedAt(ctx context.Context, obj *model.DashboardLock) (string, error) {
	return obj.LockedAt.Format(time.RFC3339), nil
}

// ExpiresAt is the resolver for the expiresAt field.
func (r *dashboardLockResolver) ExpiresAt(ctx context.Context, obj *model.DashboardLock) (string, error) {
	return obj.ExpiresAt.Format(time.RFC3339), nil
}

// CreatedAt resolves the createdAt field for DashboardWidget
func (r *dashboardWidgetResolver) CreatedAt(ctx context.Context, obj *model.DashboardWidget) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt resolves the updatedAt field for DashboardWidget
func (r *dashboardWidgetResolver) UpdatedAt(ctx context.Context, obj *model.DashboardWidget) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// CreatedAt resolves the createdAt field for LibraryWidget
func (r *libraryWidgetResolver) CreatedAt(ctx context.Context, obj *model.LibraryWidget) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt resolves the updatedAt field for LibraryWidget
func (r *libraryWidgetResolver) UpdatedAt(ctx context.Context, obj *model.LibraryWidget) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// PublishedAt resolves the publishedAt field for LibraryWidget
func (r *libraryWidgetResolver) PublishedAt(ctx context.Context, obj *model.LibraryWidget) (*string, error) {
	if obj.PublishedAt == nil {
		return nil, nil
	}
	result := obj.PublishedAt.Format(time.RFC3339)
	return &result, nil
}

// CreateSystem is the resolver for the createSystem field.
func (r *mutationResolver) CreateSystem(ctx context.Context, namespace string, name string, description *string, owner string) (*model.System, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	namespace = strings.ToUpper(strings.TrimSpace(namespace))

	existing, err := r.Repo.GetSystemByNamespace(ctx, namespace)
	if err != nil {
		return nil, fmt.Errorf("db error: %w", err)
	}
	if existing != nil {
		return nil, fmt.Errorf("namespace already exists")
	}

	err = r.RBACClient.AssignSystemOwner(ctx, callerID, owner, namespace)
	if err != nil {
		return nil, fmt.Errorf("failed to assign owner: %w", err)
	}

	desc := ""
	if description != nil {
		desc = *description
	}
	system := &model.System{
		Namespace:   namespace,
		Name:        name,
		Description: desc,
	}

	if err := r.Repo.CreateSystem(ctx, system); err != nil {
		return nil, fmt.Errorf("failed to create system: %w", err)
	}

	return system, nil
}

// UpdateSystem is the resolver for the updateSystem field.
func (r *mutationResolver) UpdateSystem(ctx context.Context, input model1.UpdateSystemInput) (*model.System, error) {
	namespace := GetNamespace(ctx)
	if namespace == "" {
		namespace = strings.ToUpper(strings.TrimSpace(input.Namespace))
	}

	if input.Name == nil && input.Description == nil {
		return nil, fmt.Errorf("at least one of name or description must be provided")
	}

	system, err := r.Repo.UpdateSystem(ctx, namespace, input.Name, input.Description)
	if err != nil {
		return nil, fmt.Errorf("failed to update system: %w", err)
	}

	return system, nil
}

// CreateLibraryWidget is the resolver for the createLibraryWidget field.
func (r *mutationResolver) CreateLibraryWidget(ctx context.Context, input model1.CreateLibraryWidgetInput) (*model.LibraryWidget, error) {
	widget := &model.LibraryWidget{
		Name:        input.Name,
		Version:     input.Version,
		Type:        input.Type,
		TypeVersion: input.TypeVersion,
		Status:      "draft",
		Schema:      input.Schema,
		UserConfig:  input.UserConfig,
	}

	if input.Status != nil {
		widget.Status = *input.Status
	}
	if input.Datasource != nil {
		widget.Datasource = convertDatasourceInputsToModel(input.Datasource)
	}
	if input.ThumbnailURL != nil {
		widget.ThumbnailURL = *input.ThumbnailURL
	}
	if input.DisplayMode != nil {
		widget.DisplayMode = *input.DisplayMode
	}
	if input.Tags != nil {
		widget.Tags = input.Tags
	}

	result, err := r.WidgetRepo.CreateLibraryWidget(ctx, widget)
	if err != nil {
		return nil, fmt.Errorf("failed to create library widget: %w", err)
	}

	return result, nil
}

// UpdateLibraryWidget is the resolver for the updateLibraryWidget field.
func (r *mutationResolver) UpdateLibraryWidget(ctx context.Context, input model1.UpdateLibraryWidgetInput) (*model.LibraryWidget, error) {
	update := &repository.LibraryWidgetUpdate{}

	if input.Name != nil {
		update.Name = input.Name
	}
	if input.Version != nil {
		update.Version = input.Version
	}
	if input.Type != nil {
		update.Type = input.Type
	}
	if input.TypeVersion != nil {
		update.TypeVersion = input.TypeVersion
	}
	if input.Schema != nil {
		update.Schema = input.Schema
	}
	if input.Datasource != nil {
		update.Datasource = convertDatasourceInputsToModel(input.Datasource)
	}
	if input.Status != nil {
		update.Status = input.Status
	}
	if input.ThumbnailURL != nil {
		update.ThumbnailURL = input.ThumbnailURL
	}
	if input.DisplayMode != nil {
		update.DisplayMode = input.DisplayMode
	}
	if input.Tags != nil {
		update.Tags = input.Tags
	}
	if input.UserConfig != nil {
		update.UserConfig = input.UserConfig
	}

	result, err := r.WidgetRepo.UpdateLibraryWidget(ctx, input.ID, update)
	if err != nil {
		return nil, fmt.Errorf("failed to update library widget: %w", err)
	}
	if result == nil {
		return nil, fmt.Errorf("library widget not found")
	}

	return result, nil
}

// DeleteLibraryWidget is the resolver for the deleteLibraryWidget field.
func (r *mutationResolver) DeleteLibraryWidget(ctx context.Context, id string) (bool, error) {
	err := r.WidgetRepo.DeleteLibraryWidget(ctx, id)
	if err != nil {
		return false, fmt.Errorf("failed to delete library widget: %w", err)
	}
	return true, nil
}

// CreateDashboard is the resolver for the createDashboard field.
func (r *mutationResolver) CreateDashboard(ctx context.Context, input model1.CreateDashboardInput) (*model.Dashboard, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}

	dashboard := &model.Dashboard{
		Name:        input.Name,
		Description: desc,
		CreatedBy:   callerID,
	}

	result, err := r.DashboardRepo.CreateDashboard(ctx, dashboard)
	if err != nil {
		return nil, fmt.Errorf("failed to create dashboard: %w", err)
	}

	return result, nil
}

// UpdateDashboard is the resolver for the updateDashboard field.
func (r *mutationResolver) UpdateDashboard(ctx context.Context, input model1.UpdateDashboardInput) (*model.Dashboard, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	// Check lock
	locked, err := r.DashboardRepo.IsLockedByOther(ctx, input.DashboardID, callerID)
	if err != nil {
		return nil, err
	}
	if locked {
		return nil, repository.ErrDashboardLocked
	}

	// Check status
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, input.DashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}
	if dashboard.Status != model.DashboardStatusDraft && dashboard.Status != model.DashboardStatusChanged {
		return nil, fmt.Errorf("can only update dashboard in draft or changed status")
	}

	update := &repository.DashboardUpdate{
		Name:        input.Name,
		Description: input.Description,
	}

	result, err := r.DashboardRepo.UpdateDashboard(ctx, input.DashboardID, update)
	if err != nil {
		return nil, fmt.Errorf("failed to update dashboard: %w", err)
	}

	return result, nil
}

// PublishDashboard is the resolver for the publishDashboard field.
func (r *mutationResolver) PublishDashboard(ctx context.Context, dashboardID string) (*model.Dashboard, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	dashboard, err := r.DashboardRepo.GetDashboard(ctx, dashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}

	// Validate status transition
	if dashboard.Status != model.DashboardStatusDraft && dashboard.Status != model.DashboardStatusChanged {
		return nil, fmt.Errorf("can only publish dashboard in draft or changed status")
	}

	// If publishing from changed, save to history first
	if dashboard.Status == model.DashboardStatusChanged {
		if err := r.DashboardRepo.SaveToHistory(ctx, dashboardID, callerID); err != nil {
			return nil, fmt.Errorf("failed to save history: %w", err)
		}
		// Delete old published widgets
		if err := r.DashboardRepo.DeleteWidgetsByVersion(ctx, dashboardID, "published"); err != nil {
			return nil, fmt.Errorf("failed to delete old widgets: %w", err)
		}
		// Promote draft widgets to published
		if err := r.DashboardRepo.PromoteDraftToPublished(ctx, dashboardID); err != nil {
			return nil, fmt.Errorf("failed to promote widgets: %w", err)
		}
		// Merge draft_data to main fields
		if dashboard.DraftData != nil {
			update := &repository.DashboardUpdate{}
			if dashboard.DraftData.Name != "" {
				update.Name = &dashboard.DraftData.Name
			}
			if dashboard.DraftData.Description != "" {
				update.Description = &dashboard.DraftData.Description
			}
			if _, err := r.DashboardRepo.UpdateDashboard(ctx, dashboardID, update); err != nil {
				return nil, err
			}
		}
	} else {
		// Publishing from draft - promote draft widgets to published
		if err := r.DashboardRepo.PromoteDraftToPublished(ctx, dashboardID); err != nil {
			return nil, fmt.Errorf("failed to promote widgets: %w", err)
		}
	}

	// Update status
	result, err := r.DashboardRepo.UpdateDashboardStatus(ctx, dashboardID, model.DashboardStatusPublished, "")
	if err != nil {
		return nil, fmt.Errorf("failed to update status: %w", err)
	}

	return result, nil
}

// ChangeDashboard is the resolver for the changeDashboard field.
func (r *mutationResolver) ChangeDashboard(ctx context.Context, dashboardID string) (*model.Dashboard, error) {
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, dashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}

	if dashboard.Status != model.DashboardStatusPublished {
		return nil, fmt.Errorf("can only change dashboard in published status")
	}

	// Copy published widgets to draft
	if err := r.DashboardRepo.CopyWidgetsToDraft(ctx, dashboardID); err != nil {
		return nil, fmt.Errorf("failed to copy widgets: %w", err)
	}

	// Update status
	result, err := r.DashboardRepo.UpdateDashboardStatus(ctx, dashboardID, model.DashboardStatusChanged, model.DashboardStatusPublished)
	if err != nil {
		return nil, fmt.Errorf("failed to update status: %w", err)
	}

	return result, nil
}

// DeleteDashboard is the resolver for the deleteDashboard field.
func (r *mutationResolver) DeleteDashboard(ctx context.Context, dashboardID string) (*model.Dashboard, error) {
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, dashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}

	if dashboard.Status == model.DashboardStatusTrashed {
		return nil, fmt.Errorf("dashboard is already trashed")
	}

	result, err := r.DashboardRepo.UpdateDashboardStatus(ctx, dashboardID, model.DashboardStatusTrashed, dashboard.Status)
	if err != nil {
		return nil, fmt.Errorf("failed to trash dashboard: %w", err)
	}

	return result, nil
}

// RestoreDashboard is the resolver for the restoreDashboard field.
func (r *mutationResolver) RestoreDashboard(ctx context.Context, dashboardID string) (*model.Dashboard, error) {
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, dashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}

	if dashboard.Status != model.DashboardStatusTrashed {
		return nil, fmt.Errorf("can only restore trashed dashboard")
	}

	previousStatus := dashboard.PreviousStatus
	if previousStatus == "" {
		previousStatus = model.DashboardStatusDraft
	}

	result, err := r.DashboardRepo.UpdateDashboardStatus(ctx, dashboardID, previousStatus, "")
	if err != nil {
		return nil, fmt.Errorf("failed to restore dashboard: %w", err)
	}

	return result, nil
}

// AddWidgetToDashboard is the resolver for the addWidgetToDashboard field.
func (r *mutationResolver) AddWidgetToDashboard(ctx context.Context, input model1.AddWidgetToDashboardInput) (*model.DashboardWidget, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	// Check lock
	locked, err := r.DashboardRepo.IsLockedByOther(ctx, input.DashboardID, callerID)
	if err != nil {
		return nil, err
	}
	if locked {
		return nil, repository.ErrDashboardLocked
	}

	// Check dashboard status
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, input.DashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}
	if dashboard.Status != model.DashboardStatusDraft && dashboard.Status != model.DashboardStatusChanged {
		return nil, fmt.Errorf("can only add widget in draft or changed status")
	}

	// Get library widget
	libraryWidget, err := r.WidgetRepo.GetLibraryWidget(ctx, input.LibraryWidgetID)
	if err != nil {
		return nil, err
	}
	if libraryWidget == nil {
		return nil, repository.ErrLibraryWidgetNotFound
	}

	// Determine widget version based on dashboard status
	widgetVersion := "draft"

	sortOrder := 0
	if input.SortOrder != nil {
		sortOrder = *input.SortOrder
	}

	displayMode := ""
	if input.DisplayMode != nil {
		displayMode = *input.DisplayMode
	}

	widget := &model.DashboardWidget{
		DashboardID:          input.DashboardID,
		Version:              widgetVersion,
		LibraryWidgetID:      input.LibraryWidgetID,
		LibraryWidgetVersion: input.LibraryWidgetVersion,
		Type:                 libraryWidget.Type,
		TypeVersion:          libraryWidget.TypeVersion,
		Name:                 libraryWidget.Name,
		Datasource:           libraryWidget.Datasource,
		Schema:               libraryWidget.Schema,
		DisplayMode:          displayMode,
		ConfigOverrides:      input.ConfigOverrides,
		Layout:               input.Layout,
		QueryOverrides:       input.QueryOverrides,
		SortOrder:            sortOrder,
	}

	result, err := r.DashboardRepo.AddWidgetToDashboard(ctx, widget)
	if err != nil {
		return nil, fmt.Errorf("failed to add widget: %w", err)
	}

	return result, nil
}

// UpdateDashboardWidget is the resolver for the updateDashboardWidget field.
func (r *mutationResolver) UpdateDashboardWidget(ctx context.Context, input model1.UpdateDashboardWidgetInput) (*model.DashboardWidget, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	// Get widget to find dashboard
	widget, err := r.DashboardRepo.GetDashboardWidget(ctx, input.DashboardWidgetID)
	if err != nil {
		return nil, err
	}
	if widget == nil {
		return nil, repository.ErrWidgetNotFound
	}

	// Check lock
	locked, err := r.DashboardRepo.IsLockedByOther(ctx, widget.DashboardID, callerID)
	if err != nil {
		return nil, err
	}
	if locked {
		return nil, repository.ErrDashboardLocked
	}

	// Check dashboard status
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, widget.DashboardID)
	if err != nil {
		return nil, err
	}
	if dashboard == nil {
		return nil, repository.ErrDashboardNotFound
	}
	if dashboard.Status != model.DashboardStatusDraft && dashboard.Status != model.DashboardStatusChanged {
		return nil, fmt.Errorf("can only update widget in draft or changed status")
	}

	// Only update draft version widgets
	if widget.Version != "draft" {
		return nil, fmt.Errorf("can only update draft version widget")
	}

	update := &repository.DashboardWidgetUpdate{
		ConfigOverrides: input.ConfigOverrides,
		Layout:          input.Layout,
		DisplayMode:     input.DisplayMode,
		QueryOverrides:  input.QueryOverrides,
		SortOrder:       input.SortOrder,
	}

	result, err := r.DashboardRepo.UpdateDashboardWidget(ctx, input.DashboardWidgetID, update)
	if err != nil {
		return nil, fmt.Errorf("failed to update widget: %w", err)
	}

	return result, nil
}

// RemoveDashboardWidget is the resolver for the removeDashboardWidget field.
func (r *mutationResolver) RemoveDashboardWidget(ctx context.Context, input model1.RemoveDashboardWidgetInput) (bool, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return false, err
	}

	// Get widget to find dashboard
	widget, err := r.DashboardRepo.GetDashboardWidget(ctx, input.DashboardWidgetID)
	if err != nil {
		return false, err
	}
	if widget == nil {
		return false, repository.ErrWidgetNotFound
	}

	// Check lock
	locked, err := r.DashboardRepo.IsLockedByOther(ctx, widget.DashboardID, callerID)
	if err != nil {
		return false, err
	}
	if locked {
		return false, repository.ErrDashboardLocked
	}

	// Check dashboard status
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, widget.DashboardID)
	if err != nil {
		return false, err
	}
	if dashboard == nil {
		return false, repository.ErrDashboardNotFound
	}
	if dashboard.Status != model.DashboardStatusDraft && dashboard.Status != model.DashboardStatusChanged {
		return false, fmt.Errorf("can only remove widget in draft or changed status")
	}

	// Only remove draft version widgets
	if widget.Version != "draft" {
		return false, fmt.Errorf("can only remove draft version widget")
	}

	if err := r.DashboardRepo.RemoveDashboardWidget(ctx, input.DashboardWidgetID); err != nil {
		return false, fmt.Errorf("failed to remove widget: %w", err)
	}

	return true, nil
}

// LockDashboard is the resolver for the lockDashboard field.
func (r *mutationResolver) LockDashboard(ctx context.Context, dashboardID string) (*model.DashboardLock, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	lock, err := r.DashboardRepo.LockDashboard(ctx, dashboardID, callerID, 5*time.Minute)
	if err != nil {
		return nil, err
	}

	return lock, nil
}

// UnlockDashboard is the resolver for the unlockDashboard field.
func (r *mutationResolver) UnlockDashboard(ctx context.Context, dashboardID string) (bool, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return false, err
	}

	if err := r.DashboardRepo.UnlockDashboard(ctx, dashboardID, callerID); err != nil {
		return false, err
	}

	return true, nil
}

// SystemMe is the resolver for the systemMe field.
func (r *queryResolver) SystemMe(ctx context.Context) ([]*model1.SystemWithRole, error) {
	callerID, err := GetCallerID(ctx)
	if err != nil {
		return nil, err
	}

	roles, err := r.RBACClient.GetUserRolesMe(ctx, callerID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user roles: %w", err)
	}

	namespaceRoleMap := make(map[string]string)
	var namespaces []string
	for _, role := range roles {
		if role.Namespace != "" {
			namespaceRoleMap[role.Namespace] = role.Role
			namespaces = append(namespaces, role.Namespace)
		}
	}

	if len(namespaces) == 0 {
		return []*model1.SystemWithRole{}, nil
	}

	systems, err := r.Repo.GetSystemsByNamespaces(ctx, namespaces)
	if err != nil {
		return nil, fmt.Errorf("failed to get systems: %w", err)
	}

	var result []*model1.SystemWithRole
	for _, sys := range systems {
		role := namespaceRoleMap[sys.Namespace]
		result = append(result, &model1.SystemWithRole{
			Namespace:   sys.Namespace,
			Name:        sys.Name,
			Description: &sys.Description,
			Role:        role,
		})
	}

	return result, nil
}

// SystemDetail is the resolver for the systemDetail field.
func (r *queryResolver) SystemDetail(ctx context.Context, namespace string) (*model.System, error) {
	ns := GetNamespace(ctx)
	if ns == "" {
		ns = strings.ToUpper(strings.TrimSpace(namespace))
	}

	system, err := r.Repo.GetSystemByNamespace(ctx, ns)
	if err != nil {
		return nil, fmt.Errorf("failed to get system: %w", err)
	}

	return system, nil
}

// LibraryWidgets is the resolver for the libraryWidgets field.
func (r *queryResolver) LibraryWidgets(ctx context.Context) ([]*model.LibraryWidget, error) {
	widgets, err := r.WidgetRepo.GetLibraryWidgets(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get library widgets: %w", err)
	}
	return widgets, nil
}

// LibraryWidget is the resolver for the libraryWidget field.
func (r *queryResolver) LibraryWidget(ctx context.Context, id string) (*model.LibraryWidget, error) {
	widget, err := r.WidgetRepo.GetLibraryWidget(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get library widget: %w", err)
	}
	return widget, nil
}

// Dashboards is the resolver for the dashboards field.
func (r *queryResolver) Dashboards(ctx context.Context) ([]*model.Dashboard, error) {
	dashboards, err := r.DashboardRepo.GetDashboards(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get dashboards: %w", err)
	}
	return dashboards, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context, id string) (*model.Dashboard, error) {
	dashboard, err := r.DashboardRepo.GetDashboard(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get dashboard: %w", err)
	}
	return dashboard, nil
}

// DashboardHistory is the resolver for the dashboardHistory field.
func (r *queryResolver) DashboardHistory(ctx context.Context, dashboardID string) ([]*model.DashboardHistory, error) {
	history, err := r.DashboardRepo.GetHistory(ctx, dashboardID)
	if err != nil {
		return nil, fmt.Errorf("failed to get dashboard history: %w", err)
	}
	return history, nil
}

// QueryDashboardWidgets is the resolver for the queryDashboardWidgets field.
func (r *queryResolver) QueryDashboardWidgets(ctx context.Context, dashboardID string, viewDraft *bool) ([]*model.DashboardWidget, error) {
	version := "published"
	if viewDraft != nil && *viewDraft {
		// Check if dashboard is in changed status, if so return draft version
		dashboard, err := r.DashboardRepo.GetDashboard(ctx, dashboardID)
		if err != nil {
			return nil, err
		}
		if dashboard != nil && dashboard.Status == model.DashboardStatusChanged {
			version = "draft"
		} else if dashboard != nil && dashboard.Status == model.DashboardStatusDraft {
			version = "draft"
		}
	}

	widgets, err := r.DashboardRepo.GetDashboardWidgets(ctx, dashboardID, version)
	if err != nil {
		return nil, fmt.Errorf("failed to get dashboard widgets: %w", err)
	}
	return widgets, nil
}

// QueryDashboardWidget is the resolver for the queryDashboardWidget field.
func (r *queryResolver) QueryDashboardWidget(ctx context.Context, dashboardWidgetID string) (*model.DashboardWidget, error) {
	widget, err := r.DashboardRepo.GetDashboardWidget(ctx, dashboardWidgetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get dashboard widget: %w", err)
	}
	return widget, nil
}

// Dashboard returns DashboardResolver implementation.
func (r *Resolver) Dashboard() DashboardResolver { return &dashboardResolver{r} }

// DashboardHistory returns DashboardHistoryResolver implementation.
func (r *Resolver) DashboardHistory() DashboardHistoryResolver { return &dashboardHistoryResolver{r} }

// DashboardLock returns DashboardLockResolver implementation.
func (r *Resolver) DashboardLock() DashboardLockResolver { return &dashboardLockResolver{r} }

// DashboardWidget returns DashboardWidgetResolver implementation.
func (r *Resolver) DashboardWidget() DashboardWidgetResolver { return &dashboardWidgetResolver{r} }

// LibraryWidget returns LibraryWidgetResolver implementation.
func (r *Resolver) LibraryWidget() LibraryWidgetResolver { return &libraryWidgetResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type dashboardResolver struct{ *Resolver }
type dashboardHistoryResolver struct{ *Resolver }
type dashboardLockResolver struct{ *Resolver }
type dashboardWidgetResolver struct{ *Resolver }
type libraryWidgetResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func convertDatasourceInputsToModel(inputs []*model1.DatasourceInput) []model.Datasource {
	if inputs == nil {
		return nil
	}
	result := make([]model.Datasource, len(inputs))
	for i, input := range inputs {
		result[i] = model.Datasource{
			ID:     input.ID,
			Name:   input.Name,
			Type:   input.Type,
			Config: input.Config,
		}
		if input.Description != nil {
			result[i].Description = *input.Description
		}
	}
	return result
}
